package com.klay.community.model;

public class Ads {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads.id
     *
     * @mbg.generated Wed Mar 25 17:21:46 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads.title
     *
     * @mbg.generated Wed Mar 25 17:21:46 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads.url
     *
     * @mbg.generated Wed Mar 25 17:21:46 CST 2020
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads.image
     *
     * @mbg.generated Wed Mar 25 17:21:46 CST 2020
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads.gmt_start
     *
     * @mbg.generated Wed Mar 25 17:21:46 CST 2020
     */
    private Long gmtStart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads.gmt_end
     *
     * @mbg.generated Wed Mar 25 17:21:46 CST 2020
     */
    private Long gmtEnd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads.gmt_create
     *
     * @mbg.generated Wed Mar 25 17:21:46 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads.gmt_modify
     *
     * @mbg.generated Wed Mar 25 17:21:46 CST 2020
     */
    private Long gmtModify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads.status
     *
     * @mbg.generated Wed Mar 25 17:21:46 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads.local_area
     *
     * @mbg.generated Wed Mar 25 17:21:46 CST 2020
     */
    private String localArea;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads.id
     *
     * @return the value of ads.id
     *
     * @mbg.generated Wed Mar 25 17:21:46 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads.id
     *
     * @param id the value for ads.id
     *
     * @mbg.generated Wed Mar 25 17:21:46 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads.title
     *
     * @return the value of ads.title
     *
     * @mbg.generated Wed Mar 25 17:21:46 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads.title
     *
     * @param title the value for ads.title
     *
     * @mbg.generated Wed Mar 25 17:21:46 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads.url
     *
     * @return the value of ads.url
     *
     * @mbg.generated Wed Mar 25 17:21:46 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads.url
     *
     * @param url the value for ads.url
     *
     * @mbg.generated Wed Mar 25 17:21:46 CST 2020
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads.image
     *
     * @return the value of ads.image
     *
     * @mbg.generated Wed Mar 25 17:21:46 CST 2020
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads.image
     *
     * @param image the value for ads.image
     *
     * @mbg.generated Wed Mar 25 17:21:46 CST 2020
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads.gmt_start
     *
     * @return the value of ads.gmt_start
     *
     * @mbg.generated Wed Mar 25 17:21:46 CST 2020
     */
    public Long getGmtStart() {
        return gmtStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads.gmt_start
     *
     * @param gmtStart the value for ads.gmt_start
     *
     * @mbg.generated Wed Mar 25 17:21:46 CST 2020
     */
    public void setGmtStart(Long gmtStart) {
        this.gmtStart = gmtStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads.gmt_end
     *
     * @return the value of ads.gmt_end
     *
     * @mbg.generated Wed Mar 25 17:21:46 CST 2020
     */
    public Long getGmtEnd() {
        return gmtEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads.gmt_end
     *
     * @param gmtEnd the value for ads.gmt_end
     *
     * @mbg.generated Wed Mar 25 17:21:46 CST 2020
     */
    public void setGmtEnd(Long gmtEnd) {
        this.gmtEnd = gmtEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads.gmt_create
     *
     * @return the value of ads.gmt_create
     *
     * @mbg.generated Wed Mar 25 17:21:46 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads.gmt_create
     *
     * @param gmtCreate the value for ads.gmt_create
     *
     * @mbg.generated Wed Mar 25 17:21:46 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads.gmt_modify
     *
     * @return the value of ads.gmt_modify
     *
     * @mbg.generated Wed Mar 25 17:21:46 CST 2020
     */
    public Long getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads.gmt_modify
     *
     * @param gmtModify the value for ads.gmt_modify
     *
     * @mbg.generated Wed Mar 25 17:21:46 CST 2020
     */
    public void setGmtModify(Long gmtModify) {
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads.status
     *
     * @return the value of ads.status
     *
     * @mbg.generated Wed Mar 25 17:21:46 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads.status
     *
     * @param status the value for ads.status
     *
     * @mbg.generated Wed Mar 25 17:21:46 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads.local_area
     *
     * @return the value of ads.local_area
     *
     * @mbg.generated Wed Mar 25 17:21:46 CST 2020
     */
    public String getLocalArea() {
        return localArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads.local_area
     *
     * @param localArea the value for ads.local_area
     *
     * @mbg.generated Wed Mar 25 17:21:46 CST 2020
     */
    public void setLocalArea(String localArea) {
        this.localArea = localArea == null ? null : localArea.trim();
    }
}