package com.klay.community.mapper;

import com.klay.community.model.Ads;
import com.klay.community.model.AdsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface AdsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ads
     *
     * @mbg.generated Wed Mar 25 17:21:46 CST 2020
     */
    long countByExample(AdsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ads
     *
     * @mbg.generated Wed Mar 25 17:21:46 CST 2020
     */
    int deleteByExample(AdsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ads
     *
     * @mbg.generated Wed Mar 25 17:21:46 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ads
     *
     * @mbg.generated Wed Mar 25 17:21:46 CST 2020
     */
    int insert(Ads record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ads
     *
     * @mbg.generated Wed Mar 25 17:21:46 CST 2020
     */
    int insertSelective(Ads record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ads
     *
     * @mbg.generated Wed Mar 25 17:21:46 CST 2020
     */
    List<Ads> selectByExampleWithRowbounds(AdsExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ads
     *
     * @mbg.generated Wed Mar 25 17:21:46 CST 2020
     */
    List<Ads> selectByExample(AdsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ads
     *
     * @mbg.generated Wed Mar 25 17:21:46 CST 2020
     */
    Ads selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ads
     *
     * @mbg.generated Wed Mar 25 17:21:46 CST 2020
     */
    int updateByExampleSelective(@Param("record") Ads record, @Param("example") AdsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ads
     *
     * @mbg.generated Wed Mar 25 17:21:46 CST 2020
     */
    int updateByExample(@Param("record") Ads record, @Param("example") AdsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ads
     *
     * @mbg.generated Wed Mar 25 17:21:46 CST 2020
     */
    int updateByPrimaryKeySelective(Ads record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ads
     *
     * @mbg.generated Wed Mar 25 17:21:46 CST 2020
     */
    int updateByPrimaryKey(Ads record);
}